server:
  port: 8002
  servlet:
    context-path: /monitor-login

fanyidong:
  context: http
  server: 39.108.52.40

eureka:
  instance:
    #设置服务名称
    hostname: 39.108.52.40
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/

spring:
  application:
    name: monitor-login
  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${fanyidong.server}:3306/common
    username: fanyidong
    password: dashuaibi
    #数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    #显示sql语句
    jpa:
      dashow-sql: true
  #邮件部分
  mail:
    host: smtp.qq.com
    username: monitoringmail@foxmail.com
    #发送方的授权码
    password: ljpevwaxmmrfbcge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: ture

#设置需要输出包的日志级别
logging:
  level:
    cn.fyd: debug

#mapper文件路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.fyd.monitorlogin.dao